# Read the Docs configuration file
version: 2

# Build documentation with MkDocs, Sphinx or Docusaurus
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build the documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Install Python dependencies
python:
  install:
    - requirements: docs/requirements.txt